### ISSUE TITLE
Remove/Archive oldest module

### ISSUE THREAD

**Issue by matheusmazzoni** [spotinst/terraform-spotinst-aws-connect#18]
# Description
I'm currently terraforming spotinst integrations and I have a question. Currently, there are two terraform modules for connecting AWS accounts to SpotInst, this and [`Oldest Connect AWS`](https://github.com/spotinst/terraform-spotinst-connect-aws). My suggestion/doubt would be to check the possibility of removing/archive the old [`repository`](https://github.com/spotinst/terraform-spotinst-connect-aws) so that there are no doubts when integrating using terraform. Thanks in advance :D

**Comment by anuragsharma-123** [comment]
Hello, the other module repository is made private. Thanks.
